language: python

install:
  - source devtools/travis-ci/install.sh
  - pip install -r requirements.txt
  - python setup.py install

script:
  - test-report

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.4  CONDA_PY=34
    - python=3.5  CONDA_PY=35
