language: python

notifications:
  email: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda update conda
  - conda install conda-build
  - conda config --add channels omnia
  - conda info -a

install:
  - conda create --name test-environment python=$TRAVIS_PYTHON_VERSION pyemma msmbuilder
  - source activate test-environment
  - conda build devtools/conda-recipe
  - python setup.py install

script:
#  - python msmpipeline/test_report_generation.py
  # quick test
  - quick_test

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.4  CONDA_PY=34
    - python=3.5  CONDA_PY=35
