package:
   name: msm-pipeline
   version: 0.0.1

source:
   path: ../..

build:
   preserve_egg_dir: True
   number: 0
   entry_points:
      - run-pipeline = pipeline.py:main

requirements:
   build:
      - setuptools
      - python
   run:
      - numpy
      - mdtraj
      - pyemma
      - corner

about:
   home: https://github.com/choderalab/msm-pipeline
   license: GNU Lesser General Public License v2 or later (LGPLv2+)   
