package:
   name: msmpipeline
   version: 0.0.1

source:
   path: ../..

requirements:
   build:
      - setuptools
      - python
   run:
      - numpy
      - mdtraj
      - pyemma
      - corner
      - msmbuilder

build:
   script: $PYTHON setup.py install

test:
  imports:
    - msmpipeline

about:
   home: https://github.com/choderalab/msm-pipeline
   license: GNU Lesser General Public License v2 or later (LGPLv2+)
