package:
   name: msmpipeline
   version: 0.0.1

source:
   path: ../..

requirements:
   build:
      - setuptools
      - python
      - numpy
      - mdtraj
      - pyemma
      - msmbuilder
   run:
      - python
      - numpy
      - mdtraj
      - pyemma
      - msmbuilder

build:
   script: pip install corner && $PYTHON setup.py install
   entry_points:
      - msm-pipeline = msmpipeline.pipeline:main
      - test-report = msmpipeline.test_report_generation:main
      - quick_test = msmpipeline.quick_test:test_generate_test_instance

test:
  imports:
    - msmpipeline

about:
   home: https://github.com/choderalab/msm-pipeline
   license: GNU Lesser General Public License v2 or later (LGPLv2+)
